use_frameworks!

platform :ios, '8.0'

target 'FFAuhtorKit_Category_Example' do
  pod 'FFAuhtorKit_Category', :path => '../'

  target 'FFAuhtorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
