source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/BJComponent/BJSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'FFAuhtorKit_Category_Example' do
  pod 'FFAuhtorKit_Category', :path => '../'
  
  pod 'FFAPIs'
  pod 'CTMediator'

  target 'FFAuhtorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
